
out_dir: msamcd
model: MSAMCD

criterion: BCE
out_type: logits
# Optimizer
optimizer: Adamw
lr: 0.001
weight_decay: 0.01

schedulers:
  - name: CosineAnnealingLR
    T_max: 100

msamcd_model:
  bkbn_name: 'efficientnet_v2_m'

device: cuda:1
